version: 2

formats:
  - pdf

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: requirements/pip.txt
    - requirements: requirements/docs.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# formats:
#   - pdf
#   - epub